// SPDX-License-Identifier: Apache-2.0
//! # silosuite-crypto
//!
//! Cryptographic primitives for `SiloSuite`, sharing one implementation
//! between native server-side use and browser-side use (via WASM).
//!
//! ## Design philosophy
//!
//! - **Established primitives only.** Every algorithm comes from the
//!   `RustCrypto` or dalek-cryptography projects, with BIP-39 recovery
//!   phrases from the rust-bitcoin `bip39` crate.
//! - **No userspace crypto.** This crate composes those primitives; it
//!   does not implement them.
//! - **Constant-time by default.** All comparisons of secret values use
//!   `subtle::ConstantTimeEq`. All AEAD comparisons are handled by the
//!   underlying primitive crates which are constant-time by design.
//! - **Memory zeroization.** Secret keys (`MasterKey`, derived KEKs,
//!   private keys) implement `Zeroize` and `ZeroizeOnDrop` so that
//!   ephemeral key material is wiped from memory after use.
//! - **Versioned envelopes.** Every ciphertext is prefixed with a 2-byte
//!   algorithm version so we can rotate primitives without breaking
//!   stored data.
//!
//! ## Modules
//!
//! - [`aead`]: XChaCha20-Poly1305 envelope format
//! - [`kdf`]: Argon2id key derivation with capability detection
//! - [`hkdf`]: HKDF-SHA256 (RFC 5869) with test vectors
//! - [`master_key`]: the master-key flow (signup/unlock/rewrap/recover)
//! - [`asymmetric`]: X25519 sealed boxes + Ed25519 signatures
//! - [`recovery`]: BIP-39 phrase generation and KEK derivation
//! - [`dek`]: per-resource data encryption key (DEK) helpers
//! - [`constant_time`]: constant-time comparison helpers
//!
//! ## WASM exports
//!
//! When compiled for `wasm32-unknown-unknown`, the [`wasm_bindings`]
//! module exposes JavaScript-callable wrappers around the public API.
//! TypeScript type definitions are generated by `wasm-bindgen` at build
//! time.

#![cfg_attr(not(feature = "std"), no_std)]
#![deny(unsafe_code)]
#![deny(missing_docs)]
#![warn(clippy::all)]
#![warn(clippy::pedantic)]
#![allow(clippy::module_name_repetitions)]

extern crate alloc;

pub mod aead;
pub mod asymmetric;
pub mod constant_time;
pub mod dek;
pub mod errors;
pub mod hkdf;
pub mod kdf;
pub mod master_key;
pub mod recovery;

#[cfg(target_arch = "wasm32")]
pub mod wasm_bindings;

/// Custom global allocator for the WASM build that zeroizes freed
/// memory before returning it to the allocator's free list. Closes
/// a residual-secrets-in-WASM-linear-memory class of finding. See
/// the module docs for the full rationale.
#[cfg(target_arch = "wasm32")]
mod zeroizing_alloc;

pub use errors::{CryptoError, CryptoResult};

/// AEAD envelope version constants.
///
/// All ciphertext blobs produced by this crate are prefixed with two
/// big-endian bytes that identify the algorithm and version. New versions
/// are added when primitives are rotated; old versions remain decryptable.
pub mod envelope_versions {
    /// XChaCha20-Poly1305 with 24-byte nonce.
    pub const V1_XCHACHA20_POLY1305: u16 = 0x0001;
}

/// Length constants used throughout the crate.
pub mod lengths {
    /// Symmetric key length (XChaCha20-Poly1305).
    pub const SYMMETRIC_KEY_LEN: usize = 32;
    /// XChaCha20-Poly1305 nonce length.
    pub const XCHACHA_NONCE_LEN: usize = 24;
    /// Poly1305 tag length.
    pub const POLY1305_TAG_LEN: usize = 16;
    /// Argon2id salt length.
    pub const ARGON2_SALT_LEN: usize = 16;
    /// Master key length.
    pub const MASTER_KEY_LEN: usize = 32;
    /// X25519 key length (public or private).
    pub const X25519_KEY_LEN: usize = 32;
    /// Ed25519 public/secret key length.
    pub const ED25519_KEY_LEN: usize = 32;
}
